name: 'nfl'
version: '1.0.0'
config-version: 2

profile: 'nfl'   # dbt Cloud will handle the connection

model-paths: ['models']

models:
  nfl:
    staging:
      +materialized: view  #Best practice is staging models as views

    marts:
      +materialized: table