version: 2

models:
  - name: stg_pbp
    columns:
      - name: game_id
        tests:
          - not_null
      - name: posteam
        tests:
          - not_null:
              where: "play_type_simple in ('pass','rush')"
      - name: opponent

  - name: fct_team_situation_agg
    columns:
      - name: posteam
        tests:
          - not_null
      - name: play_type_simple
        tests:
          - not_null
